### ISSUE TITLE
TODO list for porting from Windows to Linux

### ISSUE THREAD

**Issue by rhalbersma** [eygilbert/egdb_intl#1]
Below a list of all Windows specific system calls. In parenthesis the likely replacement in terms of Standard C++ or Linux specific system calls. A checked box means that the replacement has been tested. Memory and File I/O can be tested on Windows under Visual Studio. The rest on Windows under MinGW or on Linux under g++.

Memory 
- [x] `VirtualAlloc` (`std::aligned_alloc`)
- [x] `VirtualFree` (`std::free`)

File I/O
- [x] `CreateFile` (`std::fopen`)
- [x] `GetFileSize` (`std::fseek` and `std::ftell`)
- [x] `SetFilePointer` (`std::fseek`)
- [x] `ReadFile` (`std::fread`)
- [x] `CloseHandle` (`std::fclose`)

Bit twiddling
- [x] `_BitScanForward`  (`__builtin_ctz`)
- [x] `_BitScanReverse` (`__builtin_clz`)
- [x] `_BitScanForward64` (`__builtin_ctzll`)
- [x] `_BitScanReverse64` (`__builtin_clzll`)
- [x] `__popcnt` ( `__builtin_popcount`)
- [x] `__popcnt64` (`__builtin_popcountll`)

Threading
- [x] `InitializeCriticalSection` (not used)
- [x] `EnterCriticalSection` (not used)
- [x] `LeaveCriticalSection` (not used)
- [x] `_InterlockedExchange` (`std::atomic_flag` (members `test_and_set` and `clear`), `ATOMIC_FLAG_INIT`, `std::memory_order_acquire`, `std::memory_order_release` )

System information
- [x] `SYSTEM_INFO.dwPageSize` (`sysconf(_SC_PAGESIZE)`)
- [x] `SYSTEM_INFO.dwAllocationGranularity` (same as `dwPageSize`)
- [x] `MEMORYSTATUS.dwAvailPhys` (`sysconf(_SC_PHYS_PAGES) * sysconf(_SC_PAGESIZE)`)
- [x] `__cpuid` (`__builtin_cpu_supports("popcnt")`)

**Comment by eygilbert** [comment]
I think I can eliminate a few of these issues.
The 3 CriticalSection functions are #if'd out and not used. We don't need to port them.
get_page_size() is only needed for Windows because of FILE_FLAG_NO_BUFFERING. For Linux it can return 4096.

**Comment by eygilbert** [comment]
I'm not sure about AllocationGranularity. If it is trying to mimic the behavior of VirtualAlloc then the granularity can be set to 4096.

**Comment by eygilbert** [comment]
Added solutions to the table for `_InterlockedExchange`,`__cpuid`, `SYSTEM_INFO.dwPageSize`, and `MEMORYSTATUS.dwAvailPhys`

**Comment by rhalbersma** [comment]
I have pushed a commit that implements this using `std::atomic_flag` from `<atomic>`.
